### ISSUE TITLE
Structure of repository: need room for both client (HTML5/JavaScript) and server (Java)

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#1]
With the present repository layout the server code is placed directly on the root. I have made a sub-folder called "client" where I will commit the client code.

**Comment by AndreaDiNora** [comment]
Ok, we will create also a sub-folder for the sever side

**Comment by AndreaDiNora** [comment]
I  merged your branch with develop.
You can switch to develop branch if you want use an unique branch.
