### ISSUE TITLE
List organizations - query parameters

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#10]
Now accepts only organization name - not id.

This is ok - but if there are two organizations with partially the same name - they will both be returned.

**Comment by AndreaDiNora** [comment]
Done.

https://github.com/GeoSmartCity-CIP/gsc-datacatalogue/wiki/GSC-Data-Catalogue-Services#34--searchlist

**Comment by runarbe** [comment]
This has been handled in the calling library gsc.js
