### ISSUE TITLE
Persistent sort order for list requests

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#11]
Probably best if they are sorted by name?

**Comment by AndreaDiNora** [comment]
Not a problem, but ...
Are we sure that we want to bind the sort order on a specific server-side field?
Would not it be better leave the order preference to user choosing the field on we want order?

**Comment by runarbe** [comment]
You are right. This is a client issue and doesn't really matter...
