### ISSUE TITLE
Verify if organization returns users as part of response

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#12]
Otherwise it might be useful to have a mechanism to list users directly

**Comment by AndreaDiNora** [comment]
Your request is valid, but for consistency with other services, the search of users by organization, is for me another service than list organization (list user, for example). This service will have the idorg as input and return all users in that organization.

**Comment by AndreaDiNora** [comment]
See https://github.com/GeoSmartCity-CIP/gsc-datacatalogue/wiki/GSC-Data-Catalogue-Services#29-list-user

**Comment by runarbe** [comment]
Has been implemented in #16
