### ISSUE TITLE
Application section

### ISSUE THREAD

**Issue by AndreaDiNora** [GeoSmartCity-CIP/gsc-datacatalogue#13]
Hi, 
we need to add to client also the Application section.
This section is important to publish on Geoserver for two reasons:
1) Application is the container for all layers that we want publish. It is equivalent to Geoserver's workspace. For this reason application has three optional parameters for geoserver (url,username and password).
2) Application section is the right place where we can put the button to publish on geoserver, because usually we dont want publish a single layer, but some layers with a common logic (same application for example)

**Comment by runarbe** [comment]
The application issue has been addressed in #16
