### ISSUE TITLE
Publish on Geoserver

### ISSUE THREAD

**Issue by AndreaDiNora** [GeoSmartCity-CIP/gsc-datacatalogue#14]
We added to wiki some examples of datasource and dataset creation for publish to Geoserver. 

Datasource:
https://github.com/GeoSmartCity-CIP/gsc-datacatalogue/wiki/GSC-Data-Catalogue-Services#71--create

Application:
https://github.com/GeoSmartCity-CIP/gsc-datacatalogue/wiki/GSC-Data-Catalogue-Services#111-create

It is clear that you need also datasets and layers but their creation is standard.

**Comment by runarbe** [comment]
The feature to call the publish method for applications has been addressed in #16 

However, since I am not aware of appropriate parameters, it is necessary to test with the local GeoServer instance.
