### ISSUE TITLE
Column names some times not found?

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#20]
Q: The function to return column names for some layers/datasets reports that no columns could be found

Steps to reproduce:
- It works as exepected e.g. for 'Luxembourg today' and 'Test data set (4)'
- It does not work for 'gianni3'

A: There is a bug on our service that delete columns when update the dataset. So you can see the columns only on dataset not updated.

**Comment by AndreaDiNora** [comment]
Done

Test and close

**Comment by runarbe** [comment]
Resolved
