### ISSUE TITLE
Description missing on response, Group Layer web service, action: listgrp

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#21]
**Q**: The function to list group layers does not return the group layer description, also (layers appears to be missing if the layer was created with layers that do not belong to the same organization)

**A**: Is not a problem return also description.

Layers of another organization must not showed. Organization are important to aggregate data of same pilot.

**Q**: There does not appear to be any method to edit group layer name or description

**A**: Yes, this is true, if you think that is useful we can create this service.

**Comment by AndreaDiNora** [comment]
Added updategrp service. 
Check https://github.com/GeoSmartCity-CIP/gsc-datacatalogue/wiki/GSC-Data-Catalogue-Services#10-group-layer-services for the documentation

Test and close

**Comment by runarbe** [comment]
Service resolved - need to make change in client
- Separate between assignment of layers and update of group

I will notify by e-mail when I have committed and merged this into the repo

**Comment by AndreaDiNora** [comment]
I think that code on github is not updated, because the description is not sent in update request.

**Comment by AndreaDiNora** [comment]
Code has been updated but the update button on "Manage group layers" page do nothing.

**Comment by runarbe** [comment]
@AndreaDiNora The form requires description to be filled in. Otherwise the call to update the web service will fail. I have added the field as required in the form.
- Since listgrp method doesn't return description it is necessary to write something new every time
- If you add description to the response, it should work as anticipated.

**Comment by AndreaDiNora** [comment]
Done and Verified
