### ISSUE TITLE
Return type as part of Function web service, action: listfunc

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#22]
**Q**: The function that lists 'functions' does not return organization id, type

**A**: List function service require an organization as parameter, why do you need an organization id? Only function without an organization id are preconfigured admin functions showed with includeadminrecords to true. These functions are not linked to any organization.

**Q**: merely because it would be consistent with the behavior of other services. However, I can hide organization from the function form altogether and just use the current organization for all CRUD operations.

Type is missing from the response. Required to distinguish which other fields to show.

**A**: Ok

**Comment by AndreaDiNora** [comment]
Added type to response.

Test and close

**Comment by runarbe** [comment]
Resolved
