### ISSUE TITLE
Should an empty list response return status="error"?

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#25]
**Q**: General question: is it an error when there are no elements for list? Some of the response objects return error when there are no data to be returned for a list request.

Could it be ok with 'done' and an empty array. It has some consequence for how responses are parsed.

**A**: Can you give me an example?

**Q**: An error is returned if listperm is executed with role as input parameter?

**A**: Ok

**Comment by AndreaDiNora** [comment]
I modified response to uniform them.
The logic is this:
if you search an object for his id, if not found will be received an error
if you search objects for other params, if any is founded will be received an empty list.

**Comment by runarbe** [comment]
Resolved
