### ISSUE TITLE
Level of detail for response from list operation on applications

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#26]
**Q**: The function that lists applications does not list all details about the application - in order to populate the editing form this would be convenient

**A**: There is the search for id for details. If we return all details in application list we return too much data because the application config can be complex

**Q**: I now load the application using the idapplication parameter but I still do not get back any info

**A**: Ok

**Comment by AndreaDiNora** [comment]
Done.

Test and after close if all is good

**Comment by runarbe** [comment]
Resolved
