### ISSUE TITLE
Cannot list layers by organization, Layers web service, action: listlyr

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#27]
**Q**: The function to list layers does not accept organization alone as a parameter but requires specifying datasetId or layerId in addition. It would be convenient to be able to see all layers for an organization without these filters.

**A**: Ok

**Comment by AndreaDiNora** [comment]
Done.
The service is already online.

Close this issue after your tests.

**Comment by runarbe** [comment]
Closed
