### ISSUE TITLE
Response of Permissions web service, action: listperm

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#28]
**Q**: The function that lists permissions for roles returns an array without wrapping it in a response object. This is handled in the application but is different from all other Web Services.

**A**: Ok

**Comment by AndreaDiNora** [comment]
I added idrule and idpermission on response. We havent a list in this case because we have only a set of permission for role. 
This choice has be done to simplify the logic of permissions.

**Comment by runarbe** [comment]
Resolved
