### ISSUE TITLE
Register user does not accept anything but sinergis.it addresses

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#3]
@AndreaDiNora, @giannibarrotta When trying to register a user with an e-mail address other than xyz@sinergis.it a message is returned that the 'specificed email address does not exist'.

**Comment by Finrod56** [comment]
You are right, we used an internal smtp server that could only accept some email addresses. 
I just changed our code to use google smtp server, therefore you should be able to register with any email address now.
Let me know if there are further problems with this.

**Comment by runarbe** [comment]
@Finrod56 I confirm that this works now trying to register a user in the google.com domain
