### ISSUE TITLE
Force users to keep at least one organization

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#30]
![d1](https://cloud.githubusercontent.com/assets/5701303/19306768/8c8143e6-9077-11e6-819d-d13cc9999083.png)

**Q**: Login service accept username, no email. I cannot use my username to access to application. 
Is admin@geosmartcity.eu cabled?

**A**: admin@geosmartcity.eu and its password is hard-coded for development purposes

The user.login service returns user data directly and not a status message. Therefore it failed. I have now altered it so that it checks for a numeric iduser on the response – if it is present it interprets it as success.

**Q**: Problem persists after checking out most recent version

**A**: Looks like gsc.js library is out of date on server.

**Comment by runarbe** [comment]
Resolved - but need to add tolerance for user objects without organizations and without roles.

**Comment by runarbe** [comment]
@AndreaDiNora Have added checks for the existence of roles and organization on user object after successful authentication.

I will notify by e-mail when I have committed and merged this into the repo

**Comment by AndreaDiNora** [comment]
The organizations are showed and update is correct.
But there is another problem. If a user has not any organization, with the current user visibility associated to manage users function, the admin cannot assign an organization to these users.
I think that we need to add a control that does not allow to remove last organization associated to user.

**Comment by runarbe** [comment]
@AndreaDiNora I have added a restriction that shows a message when the user tries to remove the last organization.

**Comment by AndreaDiNora** [comment]
Verified
