### ISSUE TITLE
List user function does not return associated roles?

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#39]
**Q**: The list user function does not return associated roles – that means I cannot edit other users than the currently logged in one.

**A**:  User can be assigned to Roles only by admin. 

The flow is this:
Admin use listrole (4.3 Search/List)  to list all roles with all user associated, with assignrole (4.4 Assign/remove users to role) admin, can edit list users associated to a rule.

**A**: This flow is not implicit. Users can create roles that are specific to organizations – but need to have the aid from an admin to assign users to it? We need to discuss this flow.

**Comment by AndreaDiNora** [comment]
No it's not necessary go to an admin. 
Some organization's user will be have function "AssignUserToRole" and "AssignPermissionToRole" that activate same section with "listrole" for a specific organization.

**Comment by runarbe** [comment]
@AndreaDiNora This discussion will be continued under #32
