### ISSUE TITLE
Update user requires username to remain unchanged

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#4]
@AndreaDiNora, @giannibarrotta The update method in the user web service requires the username to remain unchanged. This may be intentional behavior - but in such case, what is the rationale for keeping the id parameter? As additional security?

**Comment by AndreaDiNora** [comment]
It's for a better security and for uniformity with the other services.

**Comment by runarbe** [comment]
Ok, good.
