### ISSUE TITLE
Error on Role web service, action: assignrole

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#40]
**Q**: The list role function does not return associated users – I need this list to be able to edit the number of users of an existing role

**A**: The list of users can be found on response of service.   Try:
{    "organization": "872" }
Do you have a role with user assigned?

**A**: Aparently, that was the problem. The listing works now – but an error persists whenever I try to add a new user to the SystemAdmin role:

`{"status":"error","description":"One of the specified id parameters is not a number.","request":{"idrole":1,"users":[{"iduser":1,"username":"Admin"},{"iduser":405,"username":"runar"}]}}
`
The same function works for other roles.

**Comment by AndreaDiNora** [comment]
Was a bug, i corrected it.

Test and close

**Comment by runarbe** [comment]
Resolved
