### ISSUE TITLE
Current organizations not shown when editing user: Web Service: user, action: listuser

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#43]
**Q**: bug on edit user page
- the page don't show the organizations saved for the user selected
- can you try on your local and verify if is a real bug or no?

**Comment by runarbe** [comment]
@AndreaDiNora I confirm this behavior.

The cause of it is that the listuser web service does not return an array of organizations.
- listuser only accepts a single parameter 'idorganization'
- this returns an summary array that looks like this:

`[
    {"id":"381","username":"rosa@sigte.udg.edu","email":"rosa@sigte.udg.edu"},
    {"id":"405","username":"runar","email":"runarbe@gmail.com"}
]`

From here I am not able to get the current associated organizations - they can only be retrieved through the login method on the service - and this requires the password which I do not have - and probably should not have.

Best would probably be to add organizations array on the response for the listuser web service - either for all requests - or adding a parameter iduser where it will be returned if only a single user is requested.

**Comment by AndreaDiNora** [comment]
I added organizations to user list.
I have already seen that the page is working.

**Comment by runarbe** [comment]
Excellent, resolved...
