### ISSUE TITLE
What is the parameter name for verifying a user email?

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#5]
@AndreaDiNora, @giannibarrotta No parameter name is specified in the test set specification. The error message suggets that it should be 'id'.

**Comment by AndreaDiNora** [comment]
Verify mail is not a normal service. It will be called as link in the mail sent to user. If needed we can transform the actual two params id,uuid in a json.

**Comment by runarbe** [comment]
@AndreaDiNora In such case, we can exclude it from the public API - it will only ever be used to confirm incoming links.
