### ISSUE TITLE
Parameters for a valid datasource on the gsc-catalogue host server

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#6]
@AndreaDiNora, @giannibarrotta When issuing the command listDataOrigin I suppose it is the intention that the web service shall try to connect to the remote resource and retrieve potential datasets? In this case, do you have a valid path to a directory of ESRI Shapefiles - or to a PostgreSQL/PostGIS database table?

**Comment by AndreaDiNora** [comment]
At this time, we have implemented only postgres/postgis and shapefile datasource, I will send you by e-mail the connections parameters.

**Comment by runarbe** [comment]
@AndreaDiNora That will be excellent, thank you.
