### ISSUE TITLE
What are the valid values for DatasourceType

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#8]
@AndreaDiNora, @giannibarrotta I have temporarily used
- Oracle
- ESRI Shapefile
- PostGIS

**Comment by AndreaDiNora** [comment]
We have implemented, for now, only shapefile and postgis

**Comment by runarbe** [comment]
@AndreaDiNora and the accepted keywords are exactly that? 'shapefile' and 'postgis'?

**Comment by AndreaDiNora** [comment]
"SHAPE" and "PostGIS" (is not case sensitive)

A note. You can create any type of datasource, included "Oracle". But list data origin service implemented only shape and postgis datasource type.

**Comment by runarbe** [comment]
@AndreaDiNora Excellent - thanks. We will expand the code list as things are implemented. For now I use only the two that are implemented.
